package jeuMemory;

import javax.swing.*;
import java.awt.*;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author kd974491
 */
public class InitDlg extends javax.swing.JDialog {

    /**
     * Creates new form InitDlg
     */
    
    // attributs 
    private LesJoueurs lj ; // joueur a selectionner 
    private boolean ok ; // indicateur de la fermeture 
    private int nc; // niveau du jeu 
  // accesseurs 
    
    
    public void setLj(LesJoueurs lj) {
        this.lj = lj;
    }

    public void setOk(boolean ok) {
        this.ok = ok;
    }

    public void setNc(int nc) {
        this.nc = nc;
    }
    
    
    
    
    public LesJoueurs getJoueurs() {
        return lj;
    }


    public boolean getOk() {
        return ok;
    }

    public int getNiveau() {
        return nc;
    }
    
    // constructeur
    
    public InitDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // regroupement des boutons 
        
        ButtonGroup G = new ButtonGroup(); // creation du groupe de bouton ( bouton groupé) 
        G.add(Enfant); // ajout du bouton Enfant dans le groupe G
        G.add(Debutant);// idem pour les autres
        G.add(Avance);
        G.add(Expert);
        // initialisation des attributs 
        this.lj = new LesJoueurs();
        this.ok = false ; 
        this.nc = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Enfant = new javax.swing.JRadioButton();
        Debutant = new javax.swing.JRadioButton();
        Avance = new javax.swing.JRadioButton();
        Expert = new javax.swing.JRadioButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        CaseLara = new javax.swing.JCheckBox();
        CaseJack = new javax.swing.JCheckBox();
        CaseJeanSebastien = new javax.swing.JCheckBox();
        CaseAmadeus = new javax.swing.JCheckBox();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        BPhoto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel11.setVerifyInputWhenFocusTarget(false);
        jPanel11.setLayout(new java.awt.GridLayout(1, 2));

        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("                            Choisissez la taille du Jeu");
        jLabel1.setToolTipText("");
        jPanel13.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        Enfant.setText("Enfant(4 personnages,2 familles)");
        Enfant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnfantActionPerformed(evt);
            }
        });
        jPanel3.add(Enfant);

        Debutant.setText("Débutant (10 personnages, 4 familles)");
        Debutant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebutantActionPerformed(evt);
            }
        });
        jPanel3.add(Debutant);

        Avance.setText("Avancé (18 personnages,6  familles)");
        Avance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvanceActionPerformed(evt);
            }
        });
        jPanel3.add(Avance);

        Expert.setText("Expert (32  personnages,6 familles)");
        Expert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpertActionPerformed(evt);
            }
        });
        jPanel3.add(Expert);

        jPanel13.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel13);

        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("                Choisissez les joueurs créés par défaut");
        jPanel14.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.GridLayout(4, 1));

        CaseLara.setText("Lara");
        CaseLara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseLaraActionPerformed(evt);
            }
        });
        jPanel4.add(CaseLara);

        CaseJack.setText("Jack");
        CaseJack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseJackActionPerformed(evt);
            }
        });
        jPanel4.add(CaseJack);

        CaseJeanSebastien.setText("Jean-sebastien");
        CaseJeanSebastien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseJeanSebastienActionPerformed(evt);
            }
        });
        jPanel4.add(CaseJeanSebastien);

        CaseAmadeus.setText("Amadeous");
        CaseAmadeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaseAmadeusActionPerformed(evt);
            }
        });
        jPanel4.add(CaseAmadeus);

        jPanel14.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel14);

        jPanel1.add(jPanel11, java.awt.BorderLayout.CENTER);

        jPanel12.setLayout(new java.awt.GridLayout(2, 1));

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane2.setViewportView(Edition);

        jPanel12.add(jScrollPane2);
        jPanel12.add(BPhoto);

        jPanel1.add(jPanel12, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel2.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel2.add(Valider);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnfantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnfantActionPerformed
       // TODO add your handling code here:
       this.nc = 4 ; // initialisation du niveau a  4 ;
    }//GEN-LAST:event_EnfantActionPerformed

    private void CaseLaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseLaraActionPerformed
        // TODO add your handling code here:
        Joueur j=new Joueur("Lara", "epiques"); // Creation du joueur Lara
 j.setPhoto(new ImageIcon(getClass().getResource("/memory/img/lara.jpg"))); //  creation de la photo de Lara
 this.lj.ajouteJoueur(j); // ajout du joueur choisis dans la liste 
 Edition.setText(j.toString()); // affichage de ses information dans la zone d'edition 
 Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);// redimentionnement de l'Image 
 BPhoto.setIcon(new ImageIcon(img)); // ajout de L'image sur le bouton bphoto
    }//GEN-LAST:event_CaseLaraActionPerformed

    private void DebutantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebutantActionPerformed
        // TODO add your handling code here:
        this.nc = 10; // initialisation du niveau a  10 ;
    }//GEN-LAST:event_DebutantActionPerformed

    private void AvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvanceActionPerformed
        // TODO add your handling code here:
        this.nc = 18 ; // initialisation du niveau a  18 ;
    }//GEN-LAST:event_AvanceActionPerformed

    private void ExpertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpertActionPerformed
        // TODO add your handling code here:
        this.nc = 32 ; // initialisation du niveau a  32 ;
    }//GEN-LAST:event_ExpertActionPerformed

    private void CaseJackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseJackActionPerformed
        // TODO add your handling code here:
        
            // TODO add your handling code here:
        Joueur j=new Joueur("Jack", "rares"); // Creation du joueur Jack
 j.setPhoto(new ImageIcon(getClass().getResource("/memory/img/jack.jpg"))); //  creation de la photo de Jack
 this.lj.ajouteJoueur(j); // ajout du joueur choisis dans la liste 
 Edition.setText(j.toString()); // affichage de ses information dans la zone d'edition 
 Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);// redimentionnement de l'Image 
 BPhoto.setIcon(new ImageIcon(img)); // ajout de L'image sur le bouton bphoto
    }//GEN-LAST:event_CaseJackActionPerformed

    private void CaseJeanSebastienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseJeanSebastienActionPerformed
        // TODO add your handling code here:
        
            // TODO add your handling code here:
        Joueur j=new Joueur("Jean-Sebastien", "Alpins-femmes"); // Creation du joueur Js
 j.setPhoto(new ImageIcon(getClass().getResource("/memory/img/bach.jpg"))); //  creation de la photo de Js
 this.lj.ajouteJoueur(j); // ajout du joueur choisis dans la liste 
 Edition.setText(j.toString()); // affichage de ses information dans la zone d'edition 
 Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);// redimentionnement de l'Image 
 BPhoto.setIcon(new ImageIcon(img)); // ajout de L'image sur le bouton bphoto
    }//GEN-LAST:event_CaseJeanSebastienActionPerformed

    private void CaseAmadeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaseAmadeusActionPerformed
        // TODO add your handling code here:
        
            // TODO add your handling code here:
        Joueur j=new Joueur("Amadeus", "communs"); // Creation du joueur amadeus
 j.setPhoto(new ImageIcon(getClass().getResource("/memory/img/mozart.jpg"))); //  creation de la photo de amadeus
 this.lj.ajouteJoueur(j); // ajout du joueur choisis dans la liste  
 Edition.setText(j.toString()); // affichage de ses information dans la zone d'edition 
 Image img = j.getPhoto().getImage().getScaledInstance(BPhoto.getWidth(), BPhoto.getHeight(), Image.SCALE_SMOOTH);// redimentionnement de l'Image 
 BPhoto.setIcon(new ImageIcon(img)); // ajout de L'image sur le bouton bphoto
    }//GEN-LAST:event_CaseAmadeusActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        if(!this.ok)
        {
            this.lj.supprimeJoueurs(); // suprimme tous les joueurs 
        }
        setVisible(false); // fermeture de la fenetre
        dispose() ;
    }//GEN-LAST:event_AnnulerActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
        this.ok =true ;
        setVisible(false);// fermeture de la fenetre
    }//GEN-LAST:event_ValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InitDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InitDlg dialog = new InitDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JRadioButton Avance;
    private javax.swing.JButton BPhoto;
    private javax.swing.JCheckBox CaseAmadeus;
    private javax.swing.JCheckBox CaseJack;
    private javax.swing.JCheckBox CaseJeanSebastien;
    private javax.swing.JCheckBox CaseLara;
    private javax.swing.JRadioButton Debutant;
    private javax.swing.JTextArea Edition;
    private javax.swing.JRadioButton Enfant;
    private javax.swing.JRadioButton Expert;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
