/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jeuMemory;

import javax.swing.*;
import java.awt.*;
/**
 *
 * @author kd974491
 */
public class JeuMemory extends javax.swing.JFrame {

    
    private LesPersonnages persos ; // les personnages du jeu
private LesJoueurs joueurs ;  // les joueurs du jeu 
private int l1 ,c1 ,l2 ,c2 ; 
private  Jeu monJeu ; 
    /**
     * Creates new form JeuMemory
     */

// constructeur 
    public JeuMemory() {
        initComponents();
        this.l1 = -1 ;
        this.l2 =-1 ;
        this.c1= -1 ;
        this.c2 = -1 ; 
       this.persos = new LesPersonnages(4); //  quatre  joueurs par defaut 
       this.joueurs = new LesJoueurs() ; // pour la demo ajouter des joueur avec les cartes
        
       this.monJeu = new Jeu(persos , joueurs , 4) ; 
       Recommencer.setEnabled(false);
       /*
       Joueur j=new Joueur("Lara", "epiques");
 j.setPhoto(new ImageIcon(getClass().getResource("/memory/img/lara.jpg")));
 joueurs.ajouteJoueur(j);
 j=new Joueur("Jack", "rares");
 j.setPhoto(new ImageIcon(getClass().getResource("/memory/img/jack.jpg")));
 joueurs.ajouteJoueur(j);
       */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
  
 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        NbPersosT = new javax.swing.JLabel();
        NbPersosR = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Demarrer = new javax.swing.JButton();
        Recommencer = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Parametre = new javax.swing.JMenu();
        Options = new javax.swing.JMenuItem();
        AjoutJoueur = new javax.swing.JMenuItem();
        Visualisé = new javax.swing.JMenu();
        Joueurs = new javax.swing.JMenuItem();
        Cartes = new javax.swing.JMenuItem();
        Test = new javax.swing.JMenu();
        Transfert_Test = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(3, 1));
        jPanel3.add(NbPersosT);

        NbPersosR.setText("...");
        jPanel3.add(NbPersosR);

        jLabel3.setText("...");
        jPanel3.add(jLabel3);

        jPanel1.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane2.setViewportView(Edition);

        jPanel4.add(jScrollPane2);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setLayout(new java.awt.GridLayout(1, 2));

        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        Demarrer.setText("Demarrer");
        Demarrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DemarrerActionPerformed(evt);
            }
        });
        jPanel6.add(Demarrer);

        Recommencer.setText("Recommencer");
        jPanel6.add(Recommencer);

        jPanel5.add(jPanel6);

        jPanel1.add(jPanel5, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel2.setLayout(new java.awt.GridLayout(4, 5));
        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        Parametre.setText("Parametres");

        Options.setText("Options");
        Options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionsActionPerformed(evt);
            }
        });
        Parametre.add(Options);

        AjoutJoueur.setText("Ajout Joueur");
        AjoutJoueur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutJoueurActionPerformed(evt);
            }
        });
        Parametre.add(AjoutJoueur);

        jMenuBar1.add(Parametre);

        Visualisé.setText("Visualisé");

        Joueurs.setText("Joueurs");
        Joueurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoueursActionPerformed(evt);
            }
        });
        Visualisé.add(Joueurs);

        Cartes.setText("Cartes");
        Cartes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CartesActionPerformed(evt);
            }
        });
        Visualisé.add(Cartes);

        jMenuBar1.add(Visualisé);

        Test.setText("Test");

        Transfert_Test.setText("Transfert_Test");
        Transfert_Test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Transfert_TestActionPerformed(evt);
            }
        });
        Test.add(Transfert_Test);

        jMenuBar1.add(Test);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionsActionPerformed
        // TODO add your handling code here:
        
        
        InitDlg diag= new InitDlg(this, true); // creation et affectation d'une instance InitDlg
        diag.setLocation(0,0);
        diag.setSize(800,400);
diag.setVisible(true); // ouverture de la fenetre 
if (diag.getOk()) // accesseur pour récupérer l’indicateur
{ LesJoueurs lj = diag.getJoueurs(); // accesseur pour récupérer le joueur saisi
   this.joueurs.ajouteJoueurs(lj); // on recupere par ajout  les joueurs selectionnés dans initDlg
int niveau = diag.getNiveau(); 
this.persos = new LesPersonnages(niveau); // creation d'un certain nombre de personnage selon le niveau 
// Initialliser le jeu 

this.monJeu = new Jeu(persos, joueurs , diag.getNiveau());
}
Edition.setText(this.joueurs.toString());// affichage des joueurs dans la Zone d'edition 
    }//GEN-LAST:event_OptionsActionPerformed

    private void CartesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CartesActionPerformed
        
  Joueur j=new Joueur("FanMemory", "commun");
j.initPaquetTest();
        VisuPersonnagesDlg prVisio = new VisuPersonnagesDlg(this, true ,j );//creation et affectation d'une instance VisuPersonnagesDlg
         prVisio.setSize(300,400);
         
        prVisio.setVisible(true);// ouverture de la fenettre 
        
    }//GEN-LAST:event_CartesActionPerformed

    private void JoueursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoueursActionPerformed
        // TODO add your handling code here:
        VisuJoueursDlg jrVisio =  new VisuJoueursDlg( this , true , this.joueurs ) ; 
        jrVisio.setVisible(true); // ouverture de la fenetre Joueur
    }//GEN-LAST:event_JoueursActionPerformed

    private void AjoutJoueurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutJoueurActionPerformed
       SaisieJoueurDlg AjtJoueur  = new  SaisieJoueurDlg(this , true,this.persos ); // creation d'une instance de la jDialog SaisieJoueurDlg
       AjtJoueur.setVisible(true); // ouverture de la jDialog ajout  Joueur 
       if(AjtJoueur.isOk())
       {
          this.joueurs.ajouteJoueur(AjtJoueur.getJ()); // ajout du joueur cree dans la liste des joueurs 
          
       }
    }//GEN-LAST:event_AjoutJoueurActionPerformed

    private void Transfert_TestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Transfert_TestActionPerformed
        // TODO add your handling code here:
         Joueur j1=new Joueur("FanMemory0", "commun");
 j1.initPaquetTest();
 Joueur j2=new Joueur("FanMemory1", "commun");
 j2.getPaquet().ajoutePerso(new Personnage("epiques", "burnout", 20));
 j2.getPaquet().ajoutePerso(new Personnage("epiques", "funk-ops", 30));
 j2.getPaquet().ajoutePerso(new Personnage("alpins-femmes", "mogul-master", 10));
 this.joueurs.ajouteJoueur(j1);
 this.joueurs.ajouteJoueur(j2);
 TransfertDlg diag = new TransfertDlg(this,true,joueurs,0 );
 diag.setVisible(true);
        
       
    }//GEN-LAST:event_Transfert_TestActionPerformed

    private void DemarrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DemarrerActionPerformed
      if(this.joueurs.getNbJoueurs()>=2)
      {
          Demarrer.setEnabled(false);// desactisve le bouton demarrer
          Recommencer.setEnabled(true);
          Options.setEnabled(false);
          AjoutJoueur.setEnabled(false);
          Joueurs.setEnabled(true);
          Cartes.setEnabled(false);
          int nc = this.monJeu.getPlateau().getNbc() ; // nombre de cartes 
          
          NbPersosT.setText("Nombre de personnage trouvés "+( nc-this.monJeu.getPlateau().getNbp())+"" );
          NbPersosR.setText("Nombre sde personnage restants "+this.monJeu.getPlateau().getNbp());
          
      }
      
        
        
    }//GEN-LAST:event_DemarrerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JeuMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JeuMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JeuMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JeuMemory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JeuMemory game =  new JeuMemory(); 
                game.setSize(800, 500);
                game.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AjoutJoueur;
    private javax.swing.JMenuItem Cartes;
    private javax.swing.JButton Demarrer;
    private javax.swing.JTextArea Edition;
    private javax.swing.JMenuItem Joueurs;
    private javax.swing.JLabel NbPersosR;
    private javax.swing.JLabel NbPersosT;
    private javax.swing.JMenuItem Options;
    private javax.swing.JMenu Parametre;
    private javax.swing.JButton Recommencer;
    private javax.swing.JMenu Test;
    private javax.swing.JMenuItem Transfert_Test;
    private javax.swing.JMenu Visualisé;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
