/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jeuMemory;

import javax.swing.*;
import java.awt.*; 

import java.io.* ;

/**
 *
 * @author lenovo
 */
public class SaisieJoueurDlg extends javax.swing.JDialog {

   
    // attributs 
     private  Joueur j ; // le joueur cree
     private boolean ok ; // indicateur de la fermeture 
     private ImageIcon photo  ;  // photo du joueur
     private LesPersonnages lp ; 

    private SaisieJoueurDlg(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
     
     // les getteurs

    public Joueur getJ() {
        return this.j;
    }

    public boolean isOk() {
        return this.ok;
    }
     
    
    // constructeur
    public SaisieJoueurDlg(java.awt.Frame parent, boolean modal, LesPersonnages lp) {
        super(parent, modal);
        initComponents();
        // initialisation des attributs
        this.j = new Joueur() ; 
        this.ok = false ; 
        this.lp =  lp; 
        this.photo = new ImageIcon(getClass().getResource("/memory/img/joueurDefaut.png"));
        initListeFamilles();  // Construction de la JList
        
        
        
    }
    
    
    
    
    
    // Remplissage de la JList par la liste de famille
    
    private void initListeFamilles() {       
      DefaultListModel modList= new DefaultListModel(); // creation d'un model 
              ListeFamilles.setModel(modList);// ajout du model a la jListe
  for(int i = 0 ; i<lp.getFamilles().size() ; i++)
  {
      modList.addElement(lp.getFamilles().get(i));// ajout des elements dans la liste 
  }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Pseudo = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListeFamilles = new javax.swing.JList<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Parcourir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        Photo = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        Annuler = new javax.swing.JButton();
        Valider = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("                                                              Crée votre joueur!");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Donnez votre pseudo:");
        jPanel4.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        Pseudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PseudoActionPerformed(evt);
            }
        });
        jPanel4.add(Pseudo, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Quelle est votre famille préferé de personnages?");
        jPanel5.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        ListeFamilles.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListeFamilles);

        jPanel5.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Choisissez une photo : ");
        jPanel6.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        Parcourir.setText("Parcourir");
        Parcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParcourirActionPerformed(evt);
            }
        });
        jPanel6.add(Parcourir, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));
        jPanel7.add(Photo);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel8.setLayout(new java.awt.GridLayout(1, 2));

        Annuler.setText("Annuler");
        Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerActionPerformed(evt);
            }
        });
        jPanel8.add(Annuler);

        Valider.setText("Valider");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        jPanel8.add(Valider);

        jPanel3.add(jPanel8, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParcourirActionPerformed
        // TODO add your handling code here:
          
        JFileChooser jf= new JFileChooser(); // creation de la jDialog JFileChooser
 if (jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION)
 {
 String path = jf.getSelectedFile().getPath(); // revois le chemin du fichier selectionner 
 Image img=Toolkit.getDefaultToolkit().getImage(path);// l'image est recuperer grace au chemin et stocker dans <img>
 img=img.getScaledInstance(Photo.getWidth()-10, Photo.getHeight()-10, Image.SCALE_DEFAULT); // redimentionnement de l'image 
 this.photo = new ImageIcon(img); // photo est initialiser a l'image selectionner 
 Photo.setIcon(photo); // ajout de la photo sur l'icn du bouton 
 }
        
    }//GEN-LAST:event_ParcourirActionPerformed

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
        
        if(!Pseudo.getText().equals("") && ListeFamilles.getSelectedValue()!=null ) // si pseudo et liste selectionner
        {
             this.j = new Joueur(Pseudo.getText(), ListeFamilles.getSelectedValue()) ; 
            this.ok = true ; 
             if(this.photo!=null)
             {
                 j.setPhoto(this.photo);// affecte la photo sélectionnée au joueur
                 this.setVisible(false);// fermeture de la boite de dialog 
                 dispose();// libere la memoire 
             }
            
        }
        if( Pseudo.getText().equals(""))
        {
            Pseudo.setText("  Entrer votre Pseudo !");
            
        }
    }//GEN-LAST:event_ValiderActionPerformed

    private void PseudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PseudoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PseudoActionPerformed

    private void AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerActionPerformed
        // TODO add your handling code here:
        this.ok =false ; 
        this.setVisible(false);// fermeture de la boite 
        dispose();// suppression de l'espace utiliser en memoire 
    }//GEN-LAST:event_AnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaisieJoueurDlg dialog = new SaisieJoueurDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Annuler;
    private javax.swing.JList<String> ListeFamilles;
    private javax.swing.JButton Parcourir;
    private javax.swing.JButton Photo;
    private javax.swing.JTextField Pseudo;
    private javax.swing.JButton Valider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    
}
